name: Acrolinx Content Analysis

# Trigger on various events to demonstrate different use cases
on:
  # Push events - analyze changed files
  push:
  # Pull request events - analyze PR changes
  pull_request:
    branches: [ main ]
  
  
  # Manual trigger for full repository analysis
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  statuses: write

jobs:
  # Basic content analysis job
  analyze-content:
    name: Content Quality Analysis
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for better analysis
      
      # Run Acrolinx analysis with basic configuration
      - name: Run Acrolinx Analysis
        id: acrolinx-basic
        uses: acrolinx/nextgen-analyzer@v0.0.4
        with:
          tone: formal
          dialect: american_english
          style-guide: microsoft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACROLINX_TOKEN: ${{ secrets.ACROLINX_TOKEN }}
